export const en = {
  translation: {
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'logOut': 'Log Out',
    'pleaseLogIn': "Please log-in to access all the features",

    'logIn': 'Login',
    'password': 'password',
    'credentialsErrorsMsg': "Credentials error. Please retry or create an account if you don't have one already.",
    'successfulSignUpMsg': "You account was successfully created! Please now log-in.",

    'name': "Name",
    'firstName': "First name",
    'affiliation': "Affiliation",
    'country': "Country",
    'status': "Status",
    'email': "Email",
    'passwordConfirmation': "Password confirmation",
    'terms': "Terms of use",
    'IAgreeToTerms': "I read and agreed to the terms of use.",
    'detailedDataPolicy': "The data collected in this form will be used by the PhraseoBase team (i.e. Lidilem, Université Stendhal Grenoble 3) to know its user base better, and won't sold to any third party. In accordance with the French law, you can reach to us and we will delete your personnal information.",
    'scholar': "Scholar",
    'teachingScholar': "Teaching-scholar",
    'FFLTeacher': "French foreign language teacher",
    'phdStudent': "Phd or post-Phd student",
    'student': "Student",
    'other': "Other",

    'addMissingFieldsMsg': "Please fill the missing fields and submit again",
    'addLoginTakenMsg': "This login is already taken, please take another one and submit again",
    'addErrorMsg': "An error occured, please try again later",
    'addEmailSentMsg': "Success! Please click on the validation link in the email we sent you to validate your account",

    'usePredefinedCorpus': "Use a predefined collection",
    'useCustomCorpus': "Build your own corpus",
    'useSavedCorpus': "Reuse a saved personalized corpus",

    'backToTypeSelection': "Back to type selection",
    'goToQuery': "Go to query!",

    'predefinedCorpus': "Predefined collections",
    'language': "Language",
    'collectionChoice': "Collection choice",
    'keyCaracteristics': "Key caracteristics",
    'periodColon': "Period:",
    'categoryColon': "Category:",
    'tokenNumberColon': "Tokens number:",
    'description': "Description",

    'savedCorpusHeader': "Previously saved corpuses",
    'recapInfo': "Recap information",
    'creationDate': "Creation date",

    'ready': "Ready",
    'reset': "Reset",
    'customCorpusTitle': "Create your own corpus",
    'customCorpusDesc': "Define one or more sub-corpuses, or partition one thanks to partition keys",
    'globalParams': "Global parameters",
    'corpusName': "Corpus name",
    'corpusLang': "Corpus language",
    'advancedParams': "Advanced parameters (optional)",
    'alignedLang': "Aligned language (language to which the text is translated)",
    'partSubCorpus': "Sub-corpus partition",
    'addSubCorpus': "Add a sub-corpus",
    'searchRecapColon': "Search recap:",

    'subCorpusParams': "Sub-corpus parameters",
    'subCorpusName': "Sub-corpus name",
    'collection': "Collection",
    'filters': "Filters",
    'categories': "Categories",
    'noResult': "No result",
    'filterByCategories': "Filter by categories...",
    'authors': "Authors",
    'filterByAuthors': "Filter by authors...",
    'titles': "Titles",
    'filterByTitles': "Filter by titles...",
    'sourceLangs': "Source languages (original languages of the documents)",
    'filterBySourceLangs': "Filter by source languages...",
    'titlesNumColon': "Titles number:",
    'authorsNumColon': "Authors number:",

    'partKeys': "Partition keys",
    'validate': "Validate",

    'advancedParamsBtn': "Advanced parameters",

    'typeAQuery': "Type a query",
    'go': "Go",
    'queryColon': "Query:",
    'frequencyColon': "Frequency:",
    'exampleColon': "Example:",
    'tql': "TQL (advanced query)",
    'exemplesOfAdvancedQueriesColon': "Advanced query examples:",
    'suggestionOfAdvancedQueries': "Advanced query suggestions",
    'suggestedQueriesExplanation': "Click on one of the suggestions below to generate an advanced query",
  },
};
