export const fr = {
  translation: {
    'signIn': 'Connexion',
    'signUp': 'Créer un compte',
    'logOut': 'Déconnexion',
    'pleaseLogIn': "Veuillez vous connecter pour accéder à toutes les fonctionnalités",

    'logIn': 'Identifiant',
    'password': 'Mot de passe',
    'credentialsErrorsMsg': "Identifiants incorrects. Veuillez réessayer ou créer un compte si vous n'en n'avez pas encore un.",
    'successfulSignUpMsg': "Votre compte a été créé avec succès ! Veuillez maintenant vous connecter.",

    'name': "Nom",
    'firstName': "Prénom",
    'affiliation': "Affiliation",
    'country': "Pays",
    'status': "Statut",
    'email': "Email",
    'passwordConfirmation': "Confirmation du mot de passe",
    'terms': "Conditions d'utilisation",
    'IAgreeToTerms': "Je certifie avoir pris connaissance des modalités d'accès à l'application PhraseoBase. Je m'engage à les respecter strictement et certifie l'exactitude des renseignements portés dans le présent formulaire.",
    'detailedDataPolicy': "Les informations recueillies font l’objet d’un traitement informatique destiné à l'équipe de chercheurs du Projet PhraseoRom. Ces informations n'ont pas d'autres objet que de mieux connaître les utilisateurs d'PhraseoBase. Les destinataires des données sont des membres du Laboratoire Lidilem, Université Grenoble Alpes. Conformément à la loi « informatique et libertés » du 6 janvier 1978 modifiée en 2004, vous bénéficiez d’un droit d’accès et de rectification aux informations qui vous concernent, que vous pouvez exercer en vous adressant à olivier.kraif@univ-grenoble-alpes.fr, Lidilem (ou en modifiant ces informations directement via l'interface du site). Vous pouvez également, pour des motifs légitimes, vous opposer au traitement des données vous concernant.",
    'scholar': "Chercheur",
    'teachingScholar': "Enseignant-chercheur",
    'FFLTeacher': "Enseignant FLE",
    'phdStudent': "Doctorant ou post-doctorant",
    'student': "Etudiant",
    'other': "Autre",

    'addMissingFieldsMsg': "Veuillez remplir les champs manquants puis soumettre le formulaire à nouveau",
    'addLoginTakenMsg': "Cet identifiant est déjà pris, veuillez en choisir un autre et soumettre le formulaire à nouveau",
    'addErrorMsg': "Une erreur est survenue, merci de réessayer plus tard",
    'addEmailSentMsg': "Succès ! Veuillez cliquer sur le lien de validation dans le mail que nous vous avons envoyé.",

    'usePredefinedCorpus': "Utiliser une collection prédéfinie",
    'useCustomCorpus': "Construire un corpus personnalisé",
    'useSavedCorpus': "Réutiliser un corpus personnalisé précédemment sauvegardé",

    'backToTypeSelection': "Retour à la sélection du type de corpus",
    'goToQuery': "Passer à la définition de la requête !",

    'predefinedCorpus': "Collections prédéfinies",
    'language': "Langue",
    'collectionChoice': "Choix de la collection",
    'keyCaracteristics': "Caractéristiques clés",
    // note: the colon are included on purpose to reflec the different syntax rule
    // between French (one space before) and English (no space)
    'periodColon': "Période :",
    'categoryColon': "Catégorie :",
    'tokenNumberColon': "Nombre de tokens :",
    'description': "Description",

    'savedCorpusHeader': "Corpus précédemment sauvegardés",
    'recapInfo': "Informations récapitulatives",
    'creationDate': "Date de création",

    'ready': "Prêt",
    'reset': "Réinitialiser",
    'customCorpusTitle': "Créer votre propre corpus",
    'customCorpusDesc': "Définissez un ou plusieurs sous-corpus ou partitionnez-en un grâce à des clés de partition",
    'globalParams': "Paramètres globaux",
    'corpusName': "Nom du corpus",
    'corpusLang': "Langue du corpus",
    'advancedParams': "Paramètres avancés (optionnels)",
    'alignedLang': "Langue alignée (langue dans laquelle le texte est traduit)",
    'partSubCorpus': "Partition du sous-corpus",
    'addSubCorpus': "Ajouter un sous-corpus",
    'searchRecapColon': "Récapitulatif de la recherche :",

    'subCorpusParams': "Paramètres du sous-corpus",
    'subCorpusName': "Nom du sous-corpus",
    'collection': "Collection",
    'filters': "Filtres",
    'categories': "Categories",
    'noResult': "Aucun résultat",
    'filterByCategories': "Filtrer par catégories...",
    'authors': "Auteurs",
    'filterByAuthors': "Filtrer par auteurs...",
    'titles': "Titres",
    'filterByTitles': "Filtrer par titres...",
    'sourceLangs': "Langues sources (langues originales des textes)",
    'filterBySourceLangs': "Filtrer par langues sources...",
    'titlesNumColon': "Nombre de titres :",
    'authorsNumColon': "Nombre d'auteurs :",

    'partKeys': "Clés de partition",
    'validate': "Valider",

    'advancedParamsBtn': "Paramètres avancés",

    'typeAQuery': "Entrer une requête",
    'go': "Lancer",
    'queryColon': "Requête :",
    'frequencyColon': "Fréquence :",
    'exampleColon': "Exemple :",
    'tql': "TQL (requête avancée)",
    'exemplesOfAdvancedQueriesColon': "Exemples de requêtes avancées :",
    'suggestionOfAdvancedQueries': "Suggestion de requêtes avancées",
    'suggestedQueriesExplanation': "Cliquez sur une des suggestions ci-dessous pour générer automatiquement une requête avancée",

    'stats': "Statistiques",
    'conc': "Concordances",
    'cooc': "Cooccurrences",
    'ws': "Word Sketch",
    'recap': "Récap",

    'global': "Global",
    'searchSpace': "Espace de recherche",
    'sentencesToParseColon': "Phrases à parser :",
    'sentencesParsedColon': "Phrases parsées :",
    'searchResults': "Résultats de recherche",
    'syntheticStats': "Statistiques synthétiques",
    'dispColon': "Dispersion :",
    'instancesNumColon': "Nombre d'instances :",
    'detailedStats': "Statistiques détaillées",
    'type': 'Type',
    'dispByReal': "Dispersion par réalisation",
    'freqByReal': "Fréquence par réalisation",
    'freqByDoc': "Fréquence par document",
    'speByDoc': "Spécificité par document",

    'dispersion': "Dispersion",
    'frequency': "Fréquence",
    'specificity': "Spécificité",
    'realization': "Réalisation",
    'title': "Titre",
    'byReal': "par réalisation",
    'byDoc': "par document",
    'graphicalRepr': "Représentation graphique",
    'completeResList': "Liste complète des résultats",

    'KWIC/Unfolded': "KWIC/Déplié",
    'leftContext': "Contexte gauche",
    'node': "Nœud",
    'rightContext': "Contexte droit",

    'docMeta': "Meta-données du document",
    'tokens': "Tokens",
    'id': "Identifiant",
    'category': "Catégorie",
    'features': "Traits",
    'lemma': "Lemme",
    'form': "Forme",
    'syntaxicTree': "Arbre syntaxique",

    'corpus': "Corpus",
    'expression': "Expression",
    'collocate': "Collocatif",
    'coocNum': "Cooccurrences",
    'pivotOccNum': "Occurences du pivot",
    'collOccNum': "Occurences du collocatif",
    'relOccNum': "Occurences de la relation",
    'relation': "Relation",
    'logLike': "Log-like",

    'recapSearchAndResults': "Récapitulatif de la requête et des résultats",
    'querySentColon': "Requête envoyée (TQL) :",
    'searchArea': "Ensemble de recherche",
    'collectionColon': "Collection :",
    'categoriesColon': "Catégories : ",
    'sourceLangsColon': "Langues sources :",
    'tokenNumColon': "Nombre de tokens :",
    'caracteristics': "Caractéristiques",
    'langColon': "Langue :",
    'alignedLangColon': "Langue alignée :",
    'tokenNumToParseColon': "Tokens à parser :",
    'tokenNumParsedColon': "Tokens parsés :",
  },
};
